spring.application.name=coffee-shop-api


# =====================================
#   DATABASE
# =====================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver



#======================================
#   MinIO Configuration
#======================================
minio.public-endpoint=${MINIO_PUBLIC_ENDPOINT}
minio.internal-endpoint=${MINIO_INTERNAL_ENDPOINT}
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}
minio.bucket=${MINIO_BUCKET}
minio.region=${MINIO_REGION}
minio.presign-exp-seconds=${MINIO_PRESIGN_EXP_SECONDS}



#====================================
#   JPA / Hibernate
#====================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE



#====================================
#   Flyway Core
#====================================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0



#=====================================
#   JWT
#=====================================
jwt.secret=${JWT_SECRET}
jwt.access.expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION}



# =====================================
#   ABA
# =====================================
aba.merchantId=${ABA_MERCHANT_ID}
aba.apiKey=${ABA_API_KEY}
aba.generateQrUrl=${ABA_QR_URL}
aba.checkTransactionUrl=${ABA_CHECK_TRANSACTION_URL}
aba.callbackToken=${ABA_CALLBACK_TOKEN}
aba.callbackPublicBaseUrl=${ABA_CALLBACK_PUBLIC_BASE_URL}



#=====================================
#   Swagger Manager | turn them to false in Production
#=====================================
springdoc.swagger-ui.csrf.enabled=false
springdoc.api-docs.enabled=false



#=====================================
#   Spring Servlet Configuration
#=====================================
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

